### ISSUE TITLE
Unable to run commands with hyphens

### ISSUE THREAD

**Issue by Chirunos** [illiliti/ssu#10]
Whenever I run a command with a hyphen, it tells me I used the command wrong, for example, here, I ran `ssu neofetch -v`:
```
ssu: invalid option -- '-'
usage: ssu [-p] [-u user] -s
       ssu [-p] [-u user] -e file...
       ssu [-p] [-u user] command [args...]
```

**Comment by illiliti** [comment]
https://github.com/illiliti/ssu#note
