### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by illiliti** [illiliti/ssu#2]
Current project name has collision with SLS Linux and https://www.freshports.org/misc/sls

We need a new, easy and fast to type project name

**Comment by noocsharp** [comment]
ssu

**Comment by sdsddsd1** [comment]
`nvm` would be a cool name, though not easy to type.
I suggest `sos`.

**Comment by git-bruh** [comment]
`sus`

**Comment by illiliti** [comment]
Thanks everyone
