### ISSUE TITLE
Help: How to build?

### ISSUE THREAD

**Issue by Chirunos** [illiliti/ssu#8]
I came here looking for a simple alternative to sudo/doas and I don't know how to get the dependencies at all :(

**Comment by illiliti** [comment]
ssu depends only on what POSIX provides. If you are using e.g. linux, you don't need anything to install. Just run `make`

**Comment by Chirunos** [comment]
This is the output I get when I run make:
```
c99  -O1 -std=c99 -D_GNU_SOURCE  -Wall -Wextra -Wpedantic -Wmissing-prototypes -Wstrict-prototypes -c -o ssu.o ssu.c
make: c99: No such file or directory
make: *** [Makefile:19: ssu.o] Error 127
```
Debian 11
Make 4.3

**Comment by illiliti** [comment]
Run this instead: `make CC=cc`

**Comment by Chirunos** [comment]
Almost the same output. Using the source zip, not the tags'
```
cc  -O1 -std=c99 -D_GNU_SOURCE  -Wall -Wextra -Wpedantic -Wmissing-prototypes -Wstrict-prototypes -c -o ssu.o ssu.c
make: cc: No such file or directory
make: *** [Makefile:19: ssu.o] Error 127
```

**Comment by illiliti** [comment]
Well, you need to install gcc(or any other C99 compiler) then. It is usually pre-installed in distro, but in your case it isn't, so you need to install one.

**Comment by Chirunos** [comment]
Now works!
