### ISSUE TITLE
ssu: Operation not permitted

### ISSUE THREAD

**Issue by Chirunos** [illiliti/ssu#9]
When I run anything from ssu, I get the output mentioned above in the title

**Comment by illiliti** [comment]
Do what usage says: https://github.com/illiliti/ssu#usage. If you did already, make sure that ssu is owned by root and that permissions are set correctly.

**Comment by Chirunos** [comment]
Did what usage heading said with the following commands ("g" is my user name):
```
sudo chown root:g /usr
sudo chmod 4754 /usr
```
And with:
```
sudo chown root:g /usr/bin/ssu
sudo chmod 4754 /usr/bin/ssu
```
But I'm still getting the error.

I've built the program using `make || make CC=cc` again (I've deleted `ssu` and `ssu.o`) and then `sudo make PREFIX=/usr install` (this is the output for the second command:
```
mkdir -p     /usr/bin
cp    -f ssu /usr/bin
chown root:wheel /usr/bin/ssu
chown: invalid group: ‘root:wheel’
make: *** [Makefile:24: install] Error 1
```
By the way, when I run commands with `sudo` before `ssu`, it works fine. I think I set the wrong permissions, but I don't know which ones

**Comment by illiliti** [comment]
Why /usr and /etc? Where did you get these paths? You need to set permissions to ssu binary /usr/bin/ssu, not to some random paths.

"g" must be the group you are in, not username.

> this is the output for the second command:

This error is harmless.

**Comment by Chirunos** [comment]
>Why /usr and /etc?

Updated my comment, pasted the wrong command 😓

>"g" must be the group you are in, not username.

"g" is shown in `groups`

**Comment by illiliti** [comment]
What does `id -gn` print?

**Comment by Chirunos** [comment]
`g`

**Comment by illiliti** [comment]
Then these commands should make ssu work(assuming that ssu exists in /usr/bin/):
```
sudo chown root:g /usr/bin/ssu
sudo chmod 4754 /usr/bin/ssu
```

**Comment by Chirunos** [comment]
They don't. `ssu` is in /usr/bin

**Comment by illiliti** [comment]
If ssu is in /usr/bin, then I don't see why they wouldn't work.

Or rather, they must work in that case.

**Comment by Chirunos** [comment]
Had to make a clean install for it to work
